spring.application.name=VidrieraEmprendedores

spring.datasource.url=jdbc:postgresql://localhost:5432/emprendedores_db
spring.datasource.username=postgres
spring.datasource.password=mkdir678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Mail (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_email@gmail.com
spring.mail.password=tu_contraseña_de_aplicacion
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuración de MongoDB para fotos
spring.data.mongodb.uri=mongodb://localhost:27017/vidriera_fotos

# Opcional: Tamaño máximo para la subida de archivos (imágenes pesadas)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB