spring.application.name=VidrieraEmprendedores
server.port=${PORT:8080}

# Base de datos PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000} 
# 1 dia = 86400000 milisegundos

# Configuración de Mail (SMTP)
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuración de MongoDB para fotos
spring.data.mongodb.uri=${MONGODB_URI}

# Tamaño máximo para la subida de archivos (imágenes pesadas)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB